### ISSUE TITLE
Extending Evt

### ISSUE THREAD

**Issue by carragom** [garronej/evt#15]
Hello,

This is merely a question, no really an issue. What would be the recommended approach if I wanted to have a class that can be used as an Evt?

Some options come to mind:
1. Extend Evt. I could not find any docs about it so not sure if possible or recommended. Restrictive since it does not allow me to extend from anything else.
2. Wrap an Evt instance and expose a reduced API. Some doc about how to do it this way would be great.
3. Extend the Evt interface, wrap an instance and delegate the implementation to the wrapped instance. If this could be done in a simple way, this would be awesome because it does not disrupt my own inheritance.
4. Using mixins. In theory this could achieve something similar to the previous option, possibly better?. More information [here](https://www.typescriptlang.org/docs/handbook/mixins.html) and [here](https://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/)

Appreciate any information about this. Thanks

**Comment by garronej** [comment]
Hi @carragom 

I cooked a response under the form of a [stackblitz script](https://stackblitz.com/edit/evt-inheritence?file=index.ts). I hope I answer your questions. If I don't please let me know.

I will also update my doc as it is not the first time that someone raises this point.

Best regards

**Comment by carragom** [comment]
Thanks a lot for the quick reply, it does answer the question.

**Comment by garronej** [comment]
I am glad I answered your question :)

I made a documentation page about your question: https://docs.evt.land/extending_evt

Regards

**Comment by garronej** [comment]
Hi @carragom are you working on [JSPrimarine](https://github.com/garronej/JSPrismarine)?
