### ISSUE TITLE
Require cycles

### ISSUE THREAD

**Issue by jkolyer** [garronej/evt#2]
Require cycle: node_modules/evt/dist/lib/Evt.js -> node_modules/evt/dist/lib/EvtCore.js -> node_modules/evt/dist/lib/Ctx.js -> node_modules/evt/dist/lib/util/getLazyEvtFactory.js -> node_modules/evt/dist/lib/Evt.js

Require cycle: node_modules/evt/dist/lib/EvtCore.js -> node_modules/evt/dist/lib/Ctx.js -> node_modules/evt/dist/lib/util/getLazyEvtFactory.js -> node_modules/evt/dist/lib/EvtCore.js

Require cycle: node_modules/evt/dist/lib/Evt.js -> node_modules/evt/dist/lib/util/merge.js -> node_modules/evt/dist/lib/Evt.js

**Comment by garronej** [comment]
Thank you for reporting.
It will be nice to have these warnings gone when building react-native indeed. 😔
I will try to fix it. In the meantime, you can ignore those warning everything will work fine.

Regards

**Comment by garronej** [comment]
Hold on I should be able to fix this with dependencies injections.

**Comment by garronej** [comment]
Fixed in 1.0.17, thank you again for reporting.
