### ISSUE TITLE
bundle size is big

### ISSUE THREAD

**Issue by zhaoyao91** [garronej/evt#20]
according to [bundlephobia](https://bundlephobia.com/result?p=evt@1.9.14), `evt` is even bigger than rxjs. Could it be smaller?

**Comment by garronej** [comment]
Hi @zhaoyao91,
Thank for the notice,
Bundle size is always on my mind.  
However, there is hard choices to be made.  
I have been working on [v2](https://github.com/garronej/evt/pull/16) for a while now, it's a bit smaller than v1, the minzipped size is already about 10% lighter than rxjs but I think I will be able to better in the final release.  

Best regards

PS: If you use EVT in React you should use v2 (yarn add evt@2.0.0-beta.17)

**Comment by zhaoyao91** [comment]
I don't use react by now. So it would be even better to split react from the core package.
