### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by kbradl16** [garronej/evt#4]
Link in comment on https://github.com/garronej/evt/blob/master/src/lib/Evt.asPostable.ts#L6

“https://docs.evt.land/api/evt/aspostable” does not work, the working url is
“https://docs.evt.land/api/evt/aspospable”

**Comment by garronej** [comment]
Thank you very much for pointing this out 🙏

**Comment by garronej** [comment]
Fixed, no need to update, the link has been fixed on the doc website.
