### ISSUE TITLE
Create a new Evt after applying filter/operator

### ISSUE THREAD

**Issue by barthuijgen** [garronej/evt#57]
I'm using Evt together with [Pothos](https://pothos-graphql.dev/) graphql subscriptions, where the `subscribe` method accepts an async iterator, which Evt instances are, great!

Except now I'm trying to apply a filter or transform for the subscription, so I would have

```ts
const pingEvent = new Evt<string | null>(null);
setInterval(() => pingEvent.post(`pong ${Date.now()}`), 1000);
```
and the schema
```ts
const schema = (builder: typeof builderType) => {
  builder.subscriptionField("ping", (t) =>
    t.string({
      resolve: (parent) => parent,
      subscribe: () => pingEvent,
    })
  );
};
```

This works decently, as soon as you subscribe you get the latest value from the stateful event, which is great. But what if the first state was not published yet? I don't want to return `null` on the graphql resolver. 

I would like to be able to to something like

```ts
subscribe: () => pingEvent.attach(event => event !== null),
```

But I am not sure how to create a new instance of the Evt. 

To create my own solution I attempted the helper method

```ts
export function applyEvtFilter<
  E extends Evt<any>,
  T extends (data: UnpackEvt<E>) => boolean
>(evt: E, operator: T) {
  const newEvt = new Evt<UnpackEvt<E>>();
  evt.attach(operator, (value) => newEvt.post(value));
  return newEvt;
}
```

and doing
```ts
subscribe: () => applyEvtFilter(pingEvent, event => event !== null))
```

And while this techincally works, it no longer unsubscribes, leading to eventually print
```
MaxHandlersExceededWarning: Possible Evt memory leak detected.26 handlers attached.
```

So, how am I able to apply operators to the event stream and return a new `Evt` that still properly unsubscribes?

**Comment by garronej** [comment]
Hold on

**Comment by garronej** [comment]
This is the code if you don't need to post the initial state:  

```ts
const evtStatelessPing = (() => {

    const evtStatelessPing = Evt.create<string>();

    const ctx = Evt.newCtx();

    evtStatelessPing.evtAttach.attach(
        () => ctx.getHandlers().length === 0,
        () => evtPing
            .toStateless(ctx)
            .$attach(
                ping => ping === null ? null : [ping],
                ping => evtStatelessPing.post(ping)
            )
    );

    evtStatelessPing.evtDetach.attach(
        () => evtStatelessPing.getHandlers().length === 0,
        () => ctx.done()
    );

    return evtStatelessPing;

})();
```

**Comment by garronej** [comment]
Let me know if you need further explanation, I'm happy to answer.

**Comment by garronej** [comment]
Thanks for the kind words, they mean a lot!  
I appreciate your questions, as they help me understand the needs and experiences of users like you. It's always great to see people using EVT correctly.

> The implementation does seem overly complex for what appears to be a simple use case

I completely agree. It's unfortunate that EVT isn't more accommodating for this valid use case. I've added two items to my roadmap to address this:

- [ ] Introduce the concept of optionality for `StatefulEvt`: We'd like to have a stateful EVT that, when attached, calls the handler with its current value (which is already the case) UNLESS its current value is `null` (or something similar).
- [ ] Make it the default behavior of `pipe` to ensure that if there isn't anything attached to the downstream EVT, there isn't anything attached to the source EVT either.

> I hope performance is still fine.

I am quite confident that performance will be satisfactory. There will be a small overhead when attaching and detaching, but I believe this won't be an operation performed intensively. Additionally, the processes involved are not resource-intensive.

One final suggestion: consider abstracting this logic into a utility function to streamline the implementation.


```ts

import { Evt, type StatefulReadonlyEvt } from "evt";

/** Return a copy of the source Evt. While there isn't anything attached to the returned copy,
  *  the source evt won't be observed.  
  *  When attaching an handler to the copied Evt it will imediately be invoked with the current value
  *  of the source evt unless this value is null.
 */
function weakPipe<T>(evt: StatefulReadonlyEvt<T | null> ): Evt<T>{

	const evtOut = Evt.create<T>();

    const ctx = Evt.newCtx();

	const noSideEffect = () => { };

    evtOut.evtAttach.attach(handler => {

        if (ctx.getHandlers().length === 0) {
            evt.$attach(
                ping => ping === null ? null : [ping],
                ctx,
                ping => evtOut.post(ping)
            );
            return;
        }

        if (evt.state === null) {
            return;
        }

        const op = evtOut.getInvocableOp(handler.op);

        const result = op(evt.state, noSideEffect)

        if (result === null) {
            return;
        }

        handler.callback?.(result[0]);

    });

    evtOut.evtDetach.attach(
        () => evtOut.getHandlers().length === 0,
        () => ctx.done()
    );

    return evtOut;


}

const evtPing = Evt.create<string | null>(null);

const pingCopy= weakPipe(evtPing);
```

**Comment by garronej** [comment]
@barthuijgen I'm verry sorry.  
I should have tested the code before submiting it to you.  
I forget about:  
<img width="584" alt="image" src="https://user-images.githubusercontent.com/6702424/234130858-2af1f837-0b3f-4fbb-9faf-5d1495c6cf7f.png">

Here is the updated code:  

```ts
import { Evt, type StatefulReadonlyEvt } from "evt";

/** Return a copy of the source Evt. While there isn't anything attached to the returned copy,
  *  the source evt won't be observed.  
  *  When attaching an handler to the copied Evt it will imediately be invoked with the current value
  *  of the source evt unless this value is null.
 */
function weakPipe<T>(evt: StatefulReadonlyEvt<T | null> ): Evt<T>{

    const evtOut = Evt.create<T>();

    let ctx = Evt.newCtx();

    const noSideEffect = () => { };

    evtOut.evtAttach.attach(handler => {

        if (ctx.getHandlers().length === 0) {
            evt.$attach(
                ping => ping === null ? null : [ping],
                ctx,
                ping => evtOut.post(ping)
            );
            return;
        }

        if (evt.state === null) {
            return;
        }

        const op = evtOut.getInvocableOp(handler.op);

        const result = op(evt.state, noSideEffect)

        if (result === null) {
            return;
        }

        handler.callback?.(result[0]);

    });

    evtOut.evtDetach.attach(
        () => evtOut.getHandlers().length === 0,
        () => {
            ctx.done();
            ctx = Evt.newCtx();
        }
    );

    return evtOut;

}

const evtPing = Evt.create<string | null>(null);

const evtPingCopy= weakPipe(evtPing);
```

**Comment by garronej** [comment]
I'm sorry I wasn't able to produce a working solution.  

Here is a fix:  

```diff
-handler.callback?.(result[0])
+Promise.resolve().then(()=>handler.callback?.(result[0]));
```  

https://stackblitz.com/edit/evt-playground-7wpacg?file=index.ts

**Comment by barthuijgen** [comment]
The initial attach needed the same treatment
```ts
if (ctx.getHandlers().length === 0) {
  evt.$attach(
    (value) => (value === null ? null : [value]),
    ctx,
    (value) => Promise.resolve().then(()=> evtOut.post(value))
  );
  return;
}
```
