### ISSUE TITLE
instead of RxJS but didn't support 'window' events

### ISSUE THREAD

**Issue by mongris** [garronej/evt#9]
I was use rxjs fromEvent to subscribe 'resize' event, and used Evt.from(window, 'resize') instead of it. But it's not work. I have tried other sample like 'window.click', rxjs is works fine but nothing happening in Evt.

Does Evt.from support window events?

OS: Mac
Browser: Chrome

**Comment by garronej** [comment]
Hey,
Let me have a look

**Comment by garronej** [comment]
@mongris there is indeed a bug!
Thank you very much for reporting, I will push a fix ASAP

**Comment by mongris** [comment]
Thank you for the essential package and active response. I will move on to replace rxjs in my code with it.

**Comment by garronej** [comment]
@mongris it should be fixed now, I don't know how this remained unnoticed for so long.  
Thank you for the kind words, very much appreciated.  
Regarding using EVT on the frontend, if you use React you might be interested in checkout out [those examples](https://docs.evt.land/api/react-hooks) I recently published.  
Do not hesitate to reach again to report on your experience or if you need assistance .
